import { createTheme } from "@fluentui/react";

export const transparentTheme = createTheme({
    palette: {
        themePrimary: "#6969ff",
        themeLighterAlt: "#f9f9ff",
        themeLighter: "#e7e7ff",
        themeLight: "#d2d2ff",
        themeTertiary: "#a5a5ff",
        themeSecondary: "#7b7bff",
        themeDarkAlt: "#5e5ee6",
        themeDark: "#4f4fc2",
        themeDarker: "#3b3b8f",
        // neutralLighterAlt: "#0",
        neutralLighterAlt: "#0b0b0b",

        neutralLighter: "#0",
        neutralLight: "#0",
        neutralQuaternaryAlt: "#0",
        // neutralLighter: "#151515",
        // neutralLight: "#252525",
        // neutralQuaternaryAlt: "#2f2f2f",

        neutralQuaternary: "#373737",
        neutralTertiaryAlt: "#595959",
        neutralTertiary: "#f8f9fa",
        neutralSecondary: "#f9fafb",
        neutralSecondaryAlt: "#f9fafb",
        neutralPrimaryAlt: "#fafbfc",
        neutralPrimary: "#f5f6f7",
        neutralDark: "#fdfdfd",
        black: "#fefefe",
        // gone it since used for bacgkround color
        // white: "#000000",
        white: "#0",

    },
});
//     palette: {
//         themePrimary: "#6969ff",
//         themeLighterAlt: "#f9f9ff",
//         themeLighter: "#e7e7ff",
//         themeLight: "#d2d2ff",
//         themeTertiary: "#a5a5ff",
//         themeSecondary: "#7b7bff",
//         themeDarkAlt: "#5e5ee6",
//         themeDark: "#4f4fc2",
//         themeDarker: "#3b3b8f",
//         neutralLighterAlt: "#0b0b0b",
//         neutralLighter: "#151515",
//         neutralLight: "#252525",
//         neutralQuaternaryAlt: "#2f2f2f",
//         neutralQuaternary: "#373737",
//         neutralTertiaryAlt: "#595959",
//         neutralTertiary: "#f8f9fa",
//         neutralSecondary: "#f9fafb",
//         neutralSecondaryAlt: "#f9fafb",
//         neutralPrimaryAlt: "#fafbfc",
//         neutralPrimary: "#f5f6f7",
//         neutralDark: "#fdfdfd",
//         black: "#fefefe",
//         white: "#000000",
//     },
// });

export const myTheme = createTheme({
    palette: {
      themePrimary: '#6969ff',
      themeLighterAlt: '#f9f9ff',
      themeLighter: '#e7e7ff',
      themeLight: '#d2d2ff',
      themeTertiary: '#a5a5ff',
      themeSecondary: '#7b7bff',
      themeDarkAlt: '#5e5ee6',
      themeDark: '#4f4fc2',
      themeDarker: '#3b3b8f',
      neutralLighterAlt: '#0b0b0b',
      neutralLighter: '#151515',
      neutralLight: '#252525',
      neutralQuaternaryAlt: '#2f2f2f',
      neutralQuaternary: '#373737',
      neutralTertiaryAlt: '#595959',
      neutralTertiary: '#f0eeec',
      neutralSecondary: '#f2f1ef',
      neutralSecondaryAlt: '#f2f1ef',
      neutralPrimaryAlt: '#f5f4f2',
      neutralPrimary: '#e8e6e3',
      neutralDark: '#faf9f9',
      black: '#fcfcfc',
      white: '#000000',
    },
  });

    /* stolen from MSEdge */
export const searchBarTheme = createTheme({
    palette: {
      themePrimary: '#6969ff',
      themeLighterAlt: '#f9f9ff',
      themeLighter: '#e7e7ff',
      themeLight: '#d2d2ff',
      themeTertiary: '#a5a5ff',
      themeSecondary: '#7b7bff',
      themeDarkAlt: '#5e5ee6',
      themeDark: '#4f4fc2',
      themeDarker: '#3b3b8f',
      neutralLighterAlt: '#484848',
      neutralLighter: '#474747',
      // used as search box background color
      neutralLight: '#4a4a4a',
      neutralQuaternaryAlt: '#3f3f3f',
      neutralQuaternary: '#3c3c3c',
      neutralTertiaryAlt: '#3a3a3a',
      neutralTertiary: '#3c3c3c',
      neutralSecondary: '#e0e0e0',
      neutralSecondaryAlt: '#0',
      neutralPrimaryAlt: '#afafaf',
      neutralPrimary: '#c8c8c8',
      neutralDark: '#d4d4d4',
      black: '#e0e0e0',
      white: '#4a4a4a',
    }});

    

export const otherTheme = createTheme({
    palette: {
      themePrimary: '#6969ff',
      themeLighterAlt: '#04040a',
      themeLighter: '#111129',
      themeLight: '#1f1f4d',
      themeTertiary: '#3f3f99',
      themeSecondary: '#5c5ce0',
      themeDarkAlt: '#7878ff',
      themeDark: '#8d8dff',
      themeDarker: '#ababff',
      neutralLighterAlt: '#f8f8f8',
      neutralLighter: '#f4f4f4',
      neutralLight: '#eaeaea',
      neutralQuaternaryAlt: '#dadada',
      neutralQuaternary: '#d0d0d0',
      neutralTertiaryAlt: '#c8c8c8',
      neutralTertiary: '#595959',
      neutralSecondary: '#373737',
      neutralSecondaryAlt: '#373737',
      neutralPrimaryAlt: '#2f2f2f',
      neutralPrimary: '#000000',
      neutralDark: '#151515',
      black: '#0b0b0b',
      white: '#ffffff',
    }});